services:
  rpi-thermometer:
    build: .
    image: jhawk7/rpi-thermometer
    ports: 
      - "8080:8080"
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT="x.x.x.x:4317"
      - environment="development"
      - SERVICE_NAME="rpi-thermometer"
    devices:
      #mount i2c bus from pi for temp device
      - "/dev/i2c-1:/dev/i2c-1"