services:
  rpi-thermometer:
    build: .
    image: jhawk7/rpi-thermometer
    ports: 
      - "8080:8080"
    restart: always
    environment:
      - MQTT_SERVER="mqtt-broker"
      - MQTT_PORT="1883"
      - MQTT_USER="mqtt_user"
      - MQTT_PASS="mqtt_pass"
      - MQTT_TOPIC="topic"
    devices:
      #mount i2c bus from pi for temp device
      - "/dev/i2c-1:/dev/i2c-1"